# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

# Points to the root of Google Test, relative to where this file is.
# Remember to tweak this if you move this file.
GTEST_DIR = gtest-1.7.0

# Where to find user code.
USER_DIR = .

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $(GTEST_DIR)/include -I .

# Flags passed to the C++ compiler.
CXXFLAGS += -O2 -funroll-loops -march=native -mfpmath=sse -Wall -Wextra -pthread -std=c++11

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = LogRegOracle_test

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS) main

clean :
	rm -f $(TESTS) gtest.a gtest_main.a *.o

# Builds gtest.a and gtest_main.a.

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized.  This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

# Builds a sample test.  A test should link with either gtest.a or
# gtest_main.a, depending on whether it defines its own main()
# function.

LogRegOracle.o : $(USER_DIR)/LogRegOracle.cc $(USER_DIR)/LogRegOracle.h $(USER_DIR)/CompositeFunction.h $(USER_DIR)/special.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/LogRegOracle.cc

LogRegOracle_test.o : $(USER_DIR)/LogRegOracle_test.cc \
                     $(USER_DIR)/LogRegOracle.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/LogRegOracle_test.cc

LogRegOracle_test : LogRegOracle.o CompositeFunction.o LogRegOracle_test.o special.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

QuadraticFunction.o : $(USER_DIR)/QuadraticFunction.cc $(USER_DIR)/QuadraticFunction.h $(USER_DIR)/CompositeFunction.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/QuadraticFunction.cc

main : main.o CompositeFunction.o LogRegOracle.o QuadraticFunction.o optim.o special.o datasets.o Logger.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

main.o : $(USER_DIR)/main.cc
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/main.cc

special.o : $(USER_DIR)/special.cc $(USER_DIR)/special.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/special.cc

optim.o : $(USER_DIR)/optim.cc $(USER_DIR)/optim.h $(USER_DIR)/LogRegOracle.h $(USER_DIR)/CompositeFunction.h $(USER_DIR)/Logger.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/optim.cc

datasets.o : $(USER_DIR)/datasets.cc $(USER_DIR)/datasets.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/datasets.cc

Logger.o : $(USER_DIR)/Logger.cc $(USER_DIR)/Logger.h $(USER_DIR)/LogRegOracle.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/Logger.cc

CompositeFunction.o : $(USER_DIR)/CompositeFunction.cc $(USER_DIR)/CompositeFunction.h $(USER_DIR)/special.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/CompositeFunction.cc
